import matplotlib.pyplot as plt

def generate_plots(rhos, results_dict):
    """
    Generates comparison plots between Theory and Simulation.
    results_dict: dictionary containing data lists (sim_W, th_W, etc.)
    """
    
    # 1. Plot W (Time in System)
    plt.figure(figsize=(6,4))
    plt.plot(rhos, results_dict['th_W'], label='Theory W')
    plt.scatter(rhos, results_dict['sim_W'], s=18, label='Simulation W', color='orange')
    plt.xlabel('rho = lambda/mu')
    plt.ylabel('W')
    plt.title('W vs rho (M/M/1)')
    plt.legend()
    plt.grid(True)
    plt.show()

    # 2. Plot L (Number in System)
    plt.figure(figsize=(6,4))
    plt.plot(rhos, results_dict['th_L'], label='Theory L')
    plt.scatter(rhos, results_dict['sim_L'], s=18, label='Simulation L', color='orange')
    plt.xlabel('rho = lambda/mu')
    plt.ylabel('L')
    plt.title('L vs rho (M/M/1)')
    plt.legend()
    plt.grid(True)
    plt.show()

    # 3. Plot Wq (Time in Queue)
    plt.figure(figsize=(6,4))
    plt.plot(rhos, results_dict['th_Wq'], label='Theory Wq')
    plt.scatter(rhos, results_dict['sim_Wq'], s=18, label='Simulation Wq', color='orange')
    plt.xlabel('rho = lambda/mu')
    plt.ylabel('Wq')
    plt.title('Wq vs rho (M/M/1)')
    plt.legend()
    plt.grid(True)
    plt.show()

    # 4. Plot Lq (Number in Queue)
    plt.figure(figsize=(6,4))
    plt.plot(rhos, results_dict['th_Lq'], label='Theory Lq')
    plt.scatter(rhos, results_dict['sim_Lq'], s=18, label='Simulation Lq', color='orange')
    plt.xlabel('rho = lambda/mu')
    plt.ylabel('Lq')
    plt.title('Lq vs rho (M/M/1)')
    plt.legend()
    plt.grid(True)
    plt.show()

    # 5. Utilization Check (Input rho vs Empirical rho)
    plt.figure(figsize=(6,4))
    plt.plot(rhos, rhos, label="Input rho")
    plt.scatter(rhos, results_dict['sim_rho_emp'], s=18, label="Empirical rho", color='green')
    plt.xlabel("rho (theoretical)")
    plt.ylabel("rho (simulation)")
    plt.title("Server Utilization Check")
    plt.legend()
    plt.grid(True)
    plt.show()